#!/bin/bash
# HTCondor job submission script

# Executable
executable = venv_setup.sh

# Output files
output = /home/ubuntu/output/venv_setup.out
# Error log
error = /home/ubuntu/output/venv_setup.err
# Log file
log = /home/ubuntu/output/venv_setup.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus            = 1
request_memory          = 512MB
request_disk            = 1G

# Queue the job
queue
